name: grpc_bloc_example
description: A new Flutter project for grpc with bloc example.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  
  # intl: 
  flutter_bloc: ^8.0.1
  grpc: ^3.0.2

  formz: ^0.4.0
  equatable: ^2.0.0

  google_fonts: ^2.2.0

  avoid_keyboard: ^0.3.0
  keyboard_dismisser: ^2.0.0
  google_maps_flutter: ^2.1.6
  
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  
  permission_handler: ^9.2.0
  app_settings: ^4.1.1
  flutter_svg: ^1.0.2

  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.1
  firebase_analytics: ^9.1.9

  url_launcher: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/
    # - assets/icons/
    # - assets/onboard/
    # - assets/car_contents/
    # - assets/
# flutter_intl:
#   enabled: true
analyzer:
  strong-mode: true
  # language: 
  enableSuperMixing: true